services:
  - type: web
    name: tracelet
    runtime: python
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: CIRCLESAFE_PARENT_PASSWORD
        sync: false
      - key: CIRCLESAFE_CHILD_PASSWORD
        sync: false
